[supervisord]
nodaemon=true
user=root

[program:queue]
command=php /var/www/html/artisan horizon
autostart=true
autorestart=true
stopwaitsecs=3600
user=www-data
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
